name: Test Stash

items:
  - name: LemiGmod
    path: LemiGmod
    process: hl2.exe
    author: voidptr_t
  - name: AOSHax
    path: aoshax-v1
    process: hl2.exe
    version: 1.9
    author: Artemking4
  - name: niggers
    path: mustard
    process: hl2.exe
    version: sus edition [1.1]
