name: Artemking4's Test Stash

items:
  - name: bruh
    path: retard
    process: hl2.exe
    version: amogus edition
  - name: niggers
    path: mustard
    process: hl2.exe
    version: sus edition [1.1]