name: Cheat Loader
button:
  text: Discord server
  link: https://discord.gg/WuNgFDEXGP

items:
  - name: LemiGmod
    path: LemiGmod
    module-link: https://raw.githubusercontent.com/Sanceilaks/LemiProject/main/lemi_gmod_revolution.dll
    process: hl2.exe
    author: voidptr_t
    version: Revolution
  - name: ExecHack
    path: ExecCrack
    process: hl2.exe
    author: bitcoin
    version: Crack
  - name: OnetapGmod
    path: OnetapGmod
    process: gmod.exe
    author: KIRAT23
    version: 
  - name: CFF
    path: CFF
    process: hl2.exe
    author: 
    version: FIX
