name: Cheat Loader from discord.gg/4k7UDUZV3h
button:
  text: cum
  link: https://www.youtube.com/

items:
  - name: LemiGmod
    path: LemiGmod
    module-link: https://raw.githubusercontent.com/Sanceilaks/LemiProject/main/lemi_gmod_revolution.dll
    process: hl2.exe
    author: voidptr_t
    version: Revolution
  - name: AOSHax
    path: aoshax-v1
    process: hl2.exe
    version: 1.9
    author: Artemking4
  - name: ExecHack##1
    path: ExecCrack
    process: hl2.exe
    author: Artemking4
    version: Crack
  - name: ExecHack 
    path: EcexHackOld
    process: hl2.exe
    author: Exec
    version: Old
