name: Cheat Loader from discord.gg/4k7UDUZV3h

items:
  - name: LemiGmod
    path: LemiGmod
    process: hl2.exe
    author: voidptr_t
    version: revolution
  - name: AOSHax
    path: aoshax-v1
    process: hl2.exe
    version: 1.9
    author: Artemking4
  - name: ExecHack
    path: ExecCrack
    process: hl2.exe
    author: Artemking4
    version: Crack
